Repository KlubJagiellonski/pola-flutter, pull requests merged in 2025-03, with the labels that each got.

#158 Wyszukiwarka na głównym ekranie
  lib/analytics/analytics_event_name.dart
  lib/analytics/analytics_main_tab.dart
  lib/analytics/pola_analytics.dart
  lib/i18n/strings.g.dart
  lib/i18n/strings.i18n.json
  lib/main.dart
  lib/pages/scan/scan.dart
  lib/pages/scan/scan_navigator.dart
  lib/pages/scan/scan_search_button.dart
  test/analytics/pola_analytics_events_without_parameters_test.dart
Labels: Pola 3.0

#154 Wyniesienie generowanych plików z repozytorium
  .github/workflows/build_android.yml
  .github/workflows/build_ios.yml
  .github/workflows/tests.yml
  .gitignore
  README.md
  lib/analytics/analytics_parameters.g.dart
  lib/data/pola_api_service.chopper.dart
  lib/i18n/strings.g.dart
  lib/models/brand.g.dart
  lib/models/company.g.dart
  lib/models/donate.g.dart
  lib/models/report.g.dart
  lib/models/search_result.g.dart
  lib/pages/menu/version_bloc.freezed.dart
  lib/pages/scan/scan_event.freezed.dart
  lib/pages/scan/scan_state.freezed.dart
  lib/theme/assets.gen.dart
  lib/theme/fonts.gen.dart
  pubspec.lock
  pubspec.yaml
Labels: technical improvement

#146 ekran skanowanie guzik dotacji
  assets/scan/close_small.svg
  lib/pages/scan/companies_list.dart
  lib/pages/scan/remote_button.dart
  lib/pages/scan/scan.dart
  lib/pages/scan/scan_bloc.dart
  lib/pages/scan/scan_event.dart
  lib/pages/scan/scan_state.dart
  test/scan_bloc_test.dart
Labels: Pola 3.0, automerge
